import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { IBM_Plex_Mono } from 'next/font/google';
import Footer from '@/components/Footer';
import { Providers } from '@/components/Provider';

// const inter = Inter({ subsets: ['latin'] });
const ibmPlexMono = IBM_Plex_Mono({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${ibmPlexMono.className} grid grid-rows-[auto_1fr_auto] h-screen`}
			>
				<Navbar />
				<Providers>{children}</Providers>
				<Footer />
			</body>
		</html>
	);
}
