version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mezamateoj/ghosted
        container_name: ghosted-container
        ports:
            - '3001:3001'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
            DATABASE_URL: ${DATABASE_URL}
            CLERK_WEBHOOK_SECRET: ${CLERK_WEBHOOK_SECRET}
